import { Recipe } from "./types";

export const recipes: Recipe[] = [
  // === RECIPE CARD RECIPES (have full card graphics for popup) ===
  // mac-and-cheese removed — no full step card, was using wrong photo
  {
    slug: "lemon-butter-herb-lamb-chops",
    title: "Lemon Butter & Herb Baked Lamb Chops",
    blend: "simple-szn",
    blendLabel: "Simple Szn",
    image: "/brand/recipe-card-lamb-chops.webp",
    recipeCards: ["/brand/recipe-card-lamb-chops.webp"],
    hasRecipeCard: true,
  },
  {
    slug: "sweet-savory-marbled-mashed-potatoes",
    title: "Sweet & Savory Marbled Mashed Potatoes",
    blend: "simple-szn",
    blendLabel: "Simple Szn",
    image: "/brand/recipe-card-mashed-potatoes.webp",
    recipeCards: ["/brand/recipe-card-mashed-potatoes.webp"],
    hasRecipeCard: true,
  },
  {
    slug: "jerk-chicken-rasta-pasta",
    title: "Sweet & Spicy Jerk Chicken Rasta Pasta",
    blend: "garlicky-szn",
    blendLabel: "Garlicky",
    image: "/brand/recipe-card-jerk-rasta-pasta-1.webp",
    recipeCards: [
      "/brand/recipe-card-jerk-rasta-pasta-1.webp",
      "/brand/recipe-card-jerk-rasta-pasta-2.webp",
    ],
    hasRecipeCard: true,
  },
  {
    slug: "pepper-steak-stir-fry",
    title: "Extra Pepper Steak Stir Fry",
    blend: "garlicky-szn",
    blendLabel: "Garlicky",
    image: "/brand/recipe-card-pepper-steak-stir-fry.webp",
    recipeCards: ["/brand/recipe-card-pepper-steak-stir-fry.webp"],
    hasRecipeCard: true,
  },
  {
    slug: "any-fried-rice",
    title: "Any Fried Rice",
    blend: "holy-trinity-szn",
    blendLabel: "Holy Trinity",
    image: "/brand/recipe-card-fried-rice.webp",
    recipeCards: ["/brand/recipe-card-fried-rice.webp"],
    hasRecipeCard: true,
  },
  {
    slug: "deep-fried-salmon-fillet",
    title: "Deep Fried Salmon Fillet",
    blend: "garlicky-cajun-szn",
    blendLabel: "Garlicky + Cajun",
    image: "/brand/recipe-card-deep-fried-salmon.webp",
    recipeCards: ["/brand/recipe-card-deep-fried-salmon.webp"],
    hasRecipeCard: true,
  },
  {
    slug: "creamy-salmon-lasagna-rollups",
    title: "Creamy Salmon Lasagna Roll Ups",
    blend: "garlicky-cajun-szn",
    blendLabel: "Garlicky + Cajun",
    image: "/brand/recipe-card-salmon-lasagna-rollups-1.webp",
    recipeCards: [
      "/brand/recipe-card-salmon-lasagna-rollups-1.webp",
      "/brand/recipe-card-salmon-lasagna-rollups-2.webp",
    ],
    hasRecipeCard: true,
  },
  {
    slug: "tso-what-sauce",
    title: "Sweet & Savory Tso What Sauce",
    blend: "garlicky-szn",
    blendLabel: "Garlicky",
    image: "/brand/recipe-card-tso-what-sauce.webp",
    recipeCards: ["/brand/recipe-card-tso-what-sauce.webp"],
    hasRecipeCard: true,
  },
  {
    slug: "lump-cornbread-crabcakes",
    title: "Heavenly Lump Cornbread Crabcakes",
    blend: "garlicky-szn",
    blendLabel: "Garlicky",
    image: "/brand/recipe-card-lump-crabcakes.webp",
    recipeCards: ["/brand/recipe-card-lump-crabcakes.webp"],
    hasRecipeCard: true,
  },

  // === RAW FOOD PHOTO RECIPES (showcase only, no popup) ===
  {
    slug: "cajun-fried-chicken-poboys",
    title: "Cajun Fried Chicken Po'Boys",
    blend: "smokey-cajun-szn",
    blendLabel: "Smokey Cajun",
    image: "/food/food-cajun-poboys-fries.webp",
    hasRecipeCard: false,
  },
  {
    slug: "cajun-seared-chicken-thighs",
    title: "Cajun Seared Chicken Thighs",
    blend: "smokey-cajun-szn",
    blendLabel: "Smokey Cajun",
    image: "/food/food-seared-chicken-thighs.webp",
    hasRecipeCard: false,
  },
  {
    slug: "crispy-crab-cakes-over-grits",
    title: "Crispy Crab Cakes over Grits",
    blend: "garlicky-szn",
    blendLabel: "Garlicky",
    image: "/food/food-crabcakes-grits-mango-slaw.webp",
    hasRecipeCard: false,
  },
  // crispy-chicken-sub removed — unedited photo, out of place
  {
    slug: "open-face-fried-chicken-poboy",
    title: "Open-Face Fried Chicken Po'Boy",
    blend: "smokey-cajun-szn",
    blendLabel: "Smokey Cajun",
    image: "/food/food-open-face-chicken-poboy.webp",
    hasRecipeCard: false,
  },
  {
    slug: "craft-eatery-catering-spread",
    title: "Craft Eatery Catering Spread",
    blend: "all-blends",
    blendLabel: "All Blends",
    image: "/food/food-catering-spread.webp",
    hasRecipeCard: false,
  },
  {
    slug: "crawfish-deviled-eggs-on-kale",
    title: "Crawfish Deviled Eggs on Kale",
    blend: "smokey-cajun-szn",
    blendLabel: "Smokey Cajun",
    image: "/food/food-crawfish-deviled-eggs.webp",
    hasRecipeCard: false,
  },
  {
    slug: "naan-bowl-crispy-chickpeas",
    title: "Naan Bowl w/ Crispy Chickpeas",
    blend: "simple-szn",
    blendLabel: "Simple Szn",
    image: "/food/food-naan-bowl-chickpeas.webp",
    hasRecipeCard: false,
  },
];
